Multi Auth Revisi
himtibinus/himti-lms pull request #4
Opened 2022-07-05 13:38 UTC by abelkristv

Berikut kode revisi untuk multiauthnya kak...
Monggo di cek...

2022-07-16 09:57 UTC, NatanaelGeraldoS requested changes
Thank You @abelkristv mungkin ada sedikit minor revision aja jangan lupa validasi dan sebagainya, mohon diperbaiki saebelum di merge ya

2022-07-16 09:57 UTC, NatanaelGeraldoS commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +        $user_role_id = UserDetail::where('roleID', $user->id)->first();
Tolong Di check lagi ya @abelkristv untuk ini kayaknya bukan roleID, soalnya kalau $user->id nya 4 dia error. kayaknya harusnya userID deh
![image](https://user-images.githubusercontent.com/70951334/179349909-4e227d6d-f09b-4ec0-8512-f43890ae0ceb.png)
![image](https://user-images.githubusercontent.com/70951334/179349932-3b9b6fd6-e9d6-4ad0-b651-3c3b7bb39b35.png)

2022-07-16 09:57 UTC, NatanaelGeraldoS commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +            return redirect()->back()->withErrors("Role invalid!!");
Bisa ga kalau ditambah Page Default tanpa harus ada apa apa? karena kalo kita cek nih, pas pertama kali regist dia engga ada role. nah takutnya usernya bingung kalau role ini apa, seharusnya dia tunggu kita assign dulu kan baru dapet privilegenya

2022-07-16 09:57 UTC, NatanaelGeraldoS commented on app/Http/Requests/Auth/LoginRequest.php
> +        Hash::check($this->password, $user->password);
Ini @abelkristv Jangan lupa validasi hasil Hash::Checknya, soalnya kalau gw coba pakai password asal dia jadinya bisa masuk padahal emailnya salah wkwkw, jangan lupa di if else ya

2022-07-19 08:04 UTC, Rae-Nelvin commented
Sesuai dengan permintaan dari Natger, sepertinya masih ada beberapa yang perlu dibenerin, sehingga gw close dlu merge nya buat dibenerin. Nanti bisa di Pull Request lagi yak revisinya

2022-07-19 08:04 UTC, closed without merging