Back end Fix
himtibinus/himti-lms pull request #8
Opened 2022-07-22 16:10 UTC by abelkristv

Revisi ketiga bugs kemarin + penghapusan tailwind

2022-07-22 16:25 UTC, NatanaelGeraldoS requested changes

2022-07-22 16:25 UTC, NatanaelGeraldoS commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +            $user_role_id = UserDetail::where('userID', $user->id)->first();
Untuk ini, if elsenya jadiin gini yak, kalo ga nanti error kalo dia belum ada role
![image](https://user-images.githubusercontent.com/70951334/180482612-77f12d64-c38b-4a31-9b5f-02c1d4069e87.png)

Terus jangan lupa definisiin untuk dummynya, kalo ga errornya gini
![image](https://user-images.githubusercontent.com/70951334/180482488-ac79f9d5-445d-45d4-8671-f440ce37c99a.png)

2022-07-23 01:43 UTC, abelkristv commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +            $user_role_id = UserDetail::where('userID', $user->id)->first();
Okee ko

2022-07-23 02:25 UTC, abelkristv commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +            $user_role_id = UserDetail::where('userID', $user->id)->first();
Sudah saya revisi ko, di commit terbarunya

2022-07-23 03:17 UTC, NatanaelGeraldoS approved these changes
Ok untuk Bug-Bug kemarin sudah aman dari gw jadi gw Approve yak, thank you @abelkristv

2022-07-23 13:38 UTC, Rae-Nelvin reviewed
Di Login Request bisa dihapus2in ya cde2 yg di comment biar ga bikin kotor code

2022-07-23 13:40 UTC, Rae-Nelvin commented on database/factories/UserDetailFactory.php
> +            //'avatarID' => 1,
Ini juga bisa di hapus2in

2022-07-23 13:40 UTC, Rae-Nelvin commented
Jika sudah, basically gw udh approve, jadi tolong chat Line gw klo udah di hapus2in biar gw approve full request

2022-07-23 17:46 UTC, abelkristv commented on database/factories/UserDetailFactory.php
> +            //'avatarID' => 1,
Sudah saya hapus kak comment - comment nya

2022-07-24 15:14 UTC, merged